permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author:
  name: Wilson
  email: wenbinwb1@foxmail.com
  link: http://
  weibo: http://
  github: http://github.com/hackerwilson

# 站点信息
title: Wilson
description: Wilson's Blog
url: http://
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar:
favicon:

# google analytics 设置
ga:
  id:
  url:

# disqus 设置
disqus:
  shortname:

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates:
  - CentOS
  - Python

# 中文本地化
locals:
  tags: 标签
  about: 关于
  new: 最新文章
  archive: 归档
  content: 目录
